export const INPUT_LIMITS = {
  MEMBER_DESCRIPTION: 40,

  CLUB_NAME: 40,
  CLUB_DESCRIPTION: 500,
  CLUB_REGION: 40,
  CLUB_LINK_LABEL: 20,
  CLUB_LINK_URL: 100,
  CLUB_LINK_COUNT: 4,
  APPLY_REASON: 300,

  BOOK_STORY_TITLE: 100,
  BOOK_STORY_CONTENT: 5000,
  BOOK_STORY_COMMENT: 300,

  NOTICE_TITLE: 40,
  NOTICE_CONTENT: 1000,
  NOTICE_COMMENT: 300,
  NOTICE_POLL_OPTION: 255,
  NOTICE_POLL_OPTION_COUNT: 6,
  NOTICE_IMAGE_COUNT: 5,

  BOOKSHELF_MEETING_TITLE: 12,
  BOOKSHELF_MEETING_LOCATION: 12,
  BOOKSHELF_COMPOSER: 300,

  CHAT_MESSAGE: 400,
  REPORT_CONTENT: 500,
} as const;
