// Dummydata

import type { GroupSummary } from '@/components/base-ui/Group-Search/search_mybookclub';
import { ClubSummary } from './page';


export const mydummyGroup: GroupSummary[] = [
  { id: '1', name: '모임1' },
  { id: '2', name: '모임2' },
  { id: '3', name: '모임3' },
  { id: '4', name: '모임4' },
  { id: '1', name: '모임11241' },
  { id: '2', name: '모임51212' },
  { id: '3', name: '모임125153' },
  { id: '4', name: '모임12512514' },
  
];

export const dummyClubs: ClubSummary[] = [
  {
    clubId: 201,
    name: "오늘도 한 페이지",
    profileImageUrl: null,
    category: [1,12,13],
    public: true,
    applytype: "Yes",
    region: "서울",
    participantTypes: ["STUDENT", "MEETING"],
  },
  {
    clubId: 202,
    name: "퇴근 후 북클럽",
    profileImageUrl: null,
    category: [2,6],
    public: true,
    applytype: "Wait",
    region: "경기",
    participantTypes: ["WORKER", "OFFLINE"],
  },
  {
    clubId: 203,
    name: "새벽 독서단",
    profileImageUrl: null,
    category: [11,3],
    public: false,
    applytype: "Wait",
    region: "온라인",
    participantTypes: ["ONLINE"],
  },
  {
    clubId: 204,
    name: "고전 읽는 사람들",
    profileImageUrl: null,
    category: [4,12],
    public: true,
    applytype: "No",
    region: "부산",
    participantTypes: ["CLUB", "OFFLINE"],
  },
  {
    clubId: 205,
    name: "SF/판타지 탐험대",
    profileImageUrl: null,
    category: [13,5],
    public: true,
    applytype: "Yes",
    region: "대구",
    participantTypes: ["MEETING", "OFFLINE"],
  },
  {
    clubId: 206,
    name: "비문학 한 주 한 권",
    profileImageUrl: null,
    category: [5,11,6],
    public: true,
    applytype: "Yes",
    region: "인천",
    participantTypes: ["WORKER", "MEETING"],
  },
  {
    clubId: 207,
    name: "자기계발 실천 모임",
    profileImageUrl: null,
    category: [7],
    public: false,
    applytype: "No",
    region: "온라인",
    participantTypes: ["ONLINE", "WORKER"],
  },
  {
    clubId: 208,
    name: "시와 산책",
    profileImageUrl: null,
    category: [8],
    public: true,
    applytype: "Wait",
    region: "서울",
    participantTypes: ["STUDENT", "OFFLINE"],
  },
  {
    clubId: 209,
    name: "추리소설 연구회",
    profileImageUrl: null,
    category: [9],
    public: true,
    applytype: "Yes",
    region: "대전",
    participantTypes: ["CLUB", "MEETING"],
  },
  {
    clubId: 210,
    name: "에세이 공방",
    profileImageUrl: null,
    category: [10],
    public: true,
    applytype: "Wait",
    region: "광주",
    participantTypes: ["MEETING", "OFFLINE"],
  },
  {
    clubId: 211,
    name: "경제 뉴스 같이 읽기",
    profileImageUrl: null,
    category: [11],
    public: false,
    applytype: "No",
    region: "온라인",
    participantTypes: ["ONLINE", "WORKER"],
  },
  {
    clubId: 212,
    name: "철학 입문 스터디",
    profileImageUrl: null,
    category: [12],
    public: true,
    applytype: "Yes",
    region: "서울",
    participantTypes: ["STUDENT", "CLUB"],
  },
  {
    clubId: 213,
    name: "영어 원서 챌린지",
    profileImageUrl: null,
    category: [13],
    public: true,
    applytype: "Wait",
    region: "온라인",
    participantTypes: ["ONLINE", "STUDENT"],
  },
  {
    clubId: 214,
    name: "그림책 어른 모임",
    profileImageUrl: null,
    category: [14],
    public: true,
    applytype: "Yes",
    region: "경기",
    participantTypes: ["MEETING", "OFFLINE"],
  },
  {
    clubId: 215,
    name: "월간 책 수다방",
    profileImageUrl: null,
    category: [15],
    public: false,
    applytype: "Wait",
    region: "부산",
    participantTypes: ["CLUB", "OFFLINE"],
  },
];
